kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: px-sharedv4-sc-csi
provisioner: pxd.portworx.com
parameters:
   repl: "2"
   sharedv4: "true"
   sharedv4_svc_type: "ClusterIP"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-rwx-csi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
  storageClassName: px-sharedv4-sc-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-rwx-deployment-csi
  labels:
    app: busybox-rwx-px
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  busybox-rwx-px
  template:
    metadata:
      labels:
        app: busybox-rwx-px
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - busybox-rwx-px
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: busybox-rwx
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo $(hostname) is alive and well at $(date)! >> /mnt/busybox-rwx/status.txt ; trap : TERM INT; sleep infinity & wait']
        volumeMounts:
        - mountPath: /mnt/busybox-rwx
          name: busybox-rwx
      volumes:
      - name: busybox-rwx
        persistentVolumeClaim:
          claimName: px-rwx-csi
