kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-fbda
provisioner: pxd.portworx.com
parameters:
  backend: "pure_file"
  pure_export_rules: "*(rw)"
mountOptions:
  - nfsvers=3
  - tcp
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portworx-fbda
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
  storageClassName: portworx-fbda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-rwx-fbda
  labels:
    app: busybox-rwx-fbda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-rwx-fbda
  template:
    metadata:
      labels:
        app: busybox-rwx-fbda
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - busybox-rwx-fbda
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: busybox-rwx
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo $(hostname) is alive and well at $(date)! >> /mnt/busybox-rwx/status.txt ; trap : TERM INT; sleep infinity & wait']
        volumeMounts:
        - mountPath: /mnt/busybox-rwx
          name: busybox-rwx
      volumes:
      - name: busybox-rwx
        persistentVolumeClaim:
          claimName: portworx-fbda
